BinomialLLC/basis_universal

CMakeLists.txt

This allows to run `$BUILDTOOL install` to install `basisu` on your system, where `$BUILDTOOL` might be `ninja` or `make` for instance.

cmake: add installation target

---

webgl/transcoder/CMakeLists.txt

It looks like #7 didn't update CMakeLists.txt properly - defines
specified with -D have to be added as compile definitions.
Additionally, -O3 must be specified redundantly as a compile option and
as a link option - compile option makes .wasm bits small & fast, and
link option enables JS minifier.
After this fix CMake build results in minimal js/wasm files as well.

Fix webgl CMakeLists.txt setup

---

transcoder/basisu.h

The existing `BASISU_NO_EQUALS_OR_COPY_CONSTRUCT` forward declares the copy ctor and assignment operator, but doesn't actually prevent someone from then adding the implementation.  Additionally, the copy ctor is declared as taking a non-const reference, so someone could easily declare `X(const X&)`.
This PR corrects the parameter type on the copy constructor and explicitly declares both methods as deleted, so they _cannot_ be implemented.

Properly disable copy ctor and assignment operator

---

lodepng.cpp
transcoder/basisu.h

Hi @richgel999 !
Since MSVC does not allow linking of libaries with different iterator debug levels, this PR adds a `BASISU_NO_ITERATOR_DEBUG_LEVEL` symbol to avoid setting of `_ITERATOR_DEBUG_LEVEL` from default `2` to `1` on debug configurations. This would help the integration into [Magnum](https://github.com/mosra/magnum) a lot, as basis can then be linked to code that uses the default debug levels.
Thanks in advance!
Cheers, Jonathan.

Avoid iterator debug level mismatches for linking as library

---

.gitignore
CMakeLists.txt

Also add .gitignore to avoid versioning bin/ or a potential build/ directory
by mistake.

CMake: Fix stripping out-of-source build

---

basisu_tool.cpp

This allows external programs to confirm the existence of basisu
executable by running `basisu -version`.

Add -version argument/mode

---

basisu_comp.cpp

This is normally redundant - basisu_tool.cpp already computes the output
filename with .basis extension. However, this makes it so that if you
use -output_file command with filename without extension (for example,
one generated by mkstemp), it writes the specified filename instead of
the file with .basis appended.

Don't append .basis extension in basisu_comp.cpp

---

transcoder/basisu_transcoder.cpp

A rather trivial change -- the 1.3 MB file might be considered excessive when bundling the transcoder sources in another project, don't require it to be present when not needed.

Don't require the huge BC7m6 tables if this format is disabled

---

README.md

v1.3 of KDFS has just been published and all previous versions deprecated. This version has full documentation for PVRTC2 so I figured you'd like to update your links.

Update KDFS links to v1.3.

---

basisu_enc.h

Cf. https://github.com/godotengine/godot/issues/32384.
Build error without this patch:
```
$ cmake .. -DCMAKE_TOOLCHAIN_FILE=/usr/share/mingw/toolchain-mingw64.cmake
Initial BUILD_X64=ON
Initial CMAKE_BUILD_TYPE=
basisu build type: Release
Building 64-bit
-- Configuring done
-- Generating done
-- Build files have been written to: /home/akien/Projects/godot/godot.git/thirdparty/bu.git/build
[akien@cauldron build (master)]$ rm * -rf
[akien@cauldron build (master)]$ git up
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
From https://github.com/BinomialLLC/basis_universal
d33443a..9a63bb6  master     -> origin/master …
```

Win32: Fix build with GCC (MinGW)

---

basisu_etc.cpp

The value inside the static cast can be negative. Casting a negative floating point value to an unsigned integer is an undefined behavior and we were running into issues when executing the code with an address sanitizer turned on.
Not sure if this is the proper way to fix this but it seems to work ok. Either way, the undefined behavior should be fixed.

Fixing undefined behavior in basisu_etc.cpp

---

appveyor.yml

This PR adds an AppVeyor configuration that builds the basisu.sln with Visual Studio 2019. Example run can be [found here](https://ci.appveyor.com/project/EwoutH/basis-universal).
AppVeyor can be [enabled](https://github.com/marketplace/appveyor) on the GitHub Marketplace for BinomialLLC,

CI: Add basic AppVeyor configuration

---

basisu_enc.h

In a future version of MSVC, \<string\> doesn't transitively include\<ostream\>.
This port will compile failed with error C3861: 'tolower': identifier not found, so I add include\<ostream\> into the header file.

Include <ostream> in basisu_enc.h

---

webgl/transcoder/.gitignore
webgl/transcoder/build/basis_loader.js

Meant to contribute this a while ago, but only just got around to cleaning it up a bit.
This file provides an easy-to-use loader for basis textures with WebGL, handling all of the interaction with basis_transcoder.js/.wasm in what should generally be a pretty efficient way that just does the "right thing" for most people's needs. In general I would encourage users to make use any built-in support their rendering library of choice provides, but if it doesn't support basis yet, they want to add support to a custom renderer, or simply want a reference loader to look at this should prove useful.
Transcoding is handled in a worker, transcode formats are selected for the user automatically based on what the context supports (prioritization could probably use some tweaking), and it will silently …

Added basis_loader.js for WebGL

---

basisu.vcxproj

A few minor additions cleans-up the VS build output:
All configurations, adding the trailing slash removes: `warning MSB8004: Output Directory does not end with a trailing slash.`
Release, taking the default SDL setting removes `command line warning D9025: overriding '/sdl' with '/GS-'` and adding `_HAS_EXCEPTIONS=0` to the preprocessor defs removes the multiple: `warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc`.

Resolved various Visual Stufio warnings

---

.gitignore

Minor change but stops the need to keep manually ignoring/reverting working files in Git. No functional changes.

Ignoring VS working files and Mac finder

---

transcoder/basisu.h

The original implementation was dereferencing a nullptr which is an undefined behavior according to the C++ spec. It was triggering some automatic errors during our sanitizer tests (asan with nullptr check).
The fix replaces the offset with standard implementation of offsetof that uses compiler built in instructions when available (avoiding the undefined behavior).

Fixed undefined behavior in BASISU_OFFSETOF

---

transcoder/basisu_transcoder.cpp

With the default Xcode 11 settings, these non-functional changes remove warnings when building for iOS and Mac, notably: `Possible misuse of comma operator here` and `Implicit conversion loses integer precision: 'long' to 'int'`.
The alternative, if the original style using the comma separator is preferred, would be to add the relevant `GCC diagnostic` entries (I don't mind changing the PR to this).

Xcode 11 transcoder warnings removed

---

.reuse/dep5
LICENSES/Apache-2.0.txt
LICENSES/Zlib.txt
README.md

This PR simply wildcards files in the repository in the metainformation
.reuse/dep5 to express copyright and licensing information for files
that can't easily be parsed by REUSE. If any of the assertions made in
.reuse/dep5 are incorrect, we should fix that before this PR
is accepted.
This approach works OK, though a more intrusive, but superior version of
this PR would simplify copyright / license statements as follows, and
make sure they're present in every file:
// Copyright 2019-2020 Binomial LLC
// SPDX-License-Identifier: Apache-2.0
(or whatever the appropriate copyright owner and license are for each
file). If that were done, the wildcarding in .reuse/dep5 would not be
required to pass REUSE.
Closes #165

Make repository compliant with REUSE (https://reuse.software).

---

transcoder/basisu_transcoder.cpp

(1 << num_bits)  was converted to a signed integer that caused an overflow (as num_bits was usually set to 31). It worked fine since the value was later converted back to uint32_t but signed integer overflow is technically an undefined behavior and it was triggering errors in our automated tests.

Fixed signed integer overflow

---

spec/basis_spec.txt
transcoder/basisu_file_headers.h

Image slices have m_file_ofs. It is not relative to the start of the header, it is relative to the
start of the file. Double-check basisu_basis_file.cpp:
`m_images_descs[i].m_file_ofs = (uint32_t)cur_slice_file_ofs;`
basis_file_header has m_endpoint_cb_file_ofs. It might be easier to read if the comment on it
just said "file offset," but to clear up any confusion if someone is re-reading the spec later
this commit leaves the "relative to the" language but clarifies it. Ditto for
m_selector_cb_file_ofs.

Fix #44: document _ofs header fields

---

apg_bmp.c
basisu_etc.cpp
basisu_etc.h
jpgd.cpp

Following on from #134 this does the same for the encoder. Xcode by default enables the _shortening_ warning. There are no side effects from the changes.

Xcode encoder warnings removed

---

appveyor.yml

This change updates the CI builds to use CMake and adds builds for Linux. Unforutnately it also deprecates the MSbuild tools build but I think that's an improvement since it makes CMake the primary build system for all platforms.

Use CMake in CI

---

CMakeLists.txt

This simply fixes the following CMake warnings
```output
CMake Warning (dev) in CMakeLists.txt:
A logical block opening on the line
/Users/appveyor/projects/basis-universal/CMakeLists.txt:36 (if)
closes on the line
/Users/appveyor/projects/basis-universal/CMakeLists.txt:45 (endif)
with mis-matching arguments.
This warning is for project developers.  Use -Wno-dev to suppress it.
-- Configuring done
-- Generating done
```

Fixed CMake warnings

---

basisu_comp.cpp
basisu_comp.h
basisu_tool.cpp

Resubmit #100.
We would like to pack normal maps using GGGR which is more standard than the currently supported RRRG (using -separate_rg_to_color_alpha flag).
Added a general swizzle operator for maximum happiness.

General RGBA swizzle param

---

transcoder/basisu_transcoder.cpp

Some of our static analysis tools were complaining about unreachable code due to "#if ... return  false;  #endif code " blocks. This was changed to "#if ... return false #else ... #endif" which doesn't change the functionality but makes the static analyzers happy.
Also removed BASISU_NOTE_UNUSED on two variables that are no longer declared (resulting in a build error when BASISD_SUPPORT_UASTC was not defined)

Build and warning fixes for basisu_transcoder.cpp

---

transcoder/basisu_transcoder.cpp

Aligning with the similar feature for UASTC to BC5 path.

Fix UASTC to EAC RG11 green channel selection

---

encoder/basisu_comp.cpp

The recent changes to allow user supplied mipmaps is very useful. However, I noticed that the swizzle settings were not being applied to the custom mipmap data.

Apply swizzle to user supplied mipmaps

---

basisu_tool.cpp
encoder/basisu_comp.cpp
encoder/basisu_comp.h

This change implements -resample X Y command line support in addition to
-resample_factor, when a more sophisticated algorithm is needed to
compute the desired image size.
For example, these can be used to round the image to a multiple of 4 or
to a power of 2 for improved compatibility with various graphics APIs.
Fixes #224.

Implement custom resampling command line args

---

encoder/basisu_comp.cpp

This was the only output that was being printed when m_status_output is
false; since this defaults to true in command-line builds this doesn't
affect them.

Disable read/wrote output when status output is off

---

encoder/basisu_resampler.cpp

These aren't used and they conflict with other sources in single-source
build.

Remove redundant definitions of min/max

---

README.md

README still lists `-uastc_rdo_q` as an option, even though it has been replaced by `-uastc_rdo_l`.

Updated README to reflect current -uastc_rdo_l flag

---

encoder/apg_bmp.c

apg_bmp used implicit void*->type* cast which compiles in C but not in
C++.

apg_bmp: Fix building C source as C++

---

encoder/basisu_bc7enc.cpp
encoder/basisu_bc7enc.h

This is adding a missing #pragma once to bc7enc.h and renaming
ast_interpolate to avoid conflicts with the copy in basisu_uastc_enc
(and also making the color space obvious).

Make it easier to build Basis encoder as one .cpp

---

encoder/basisu_enc.cpp

as per title, there isn't a `<sys/timex.h>` here.  (I suspect this is the case for other BSDs too, but can't check)
tested on OpenBSD-current with clang 11, but I used a similar patch to compile godot (which bundles basis_universal) for a while already.

fix the build on OpenBSD

---

encoder/basisu_enc.cpp

Follow-up to https://github.com/BinomialLLC/basis_universal/pull/234. Downstream issues/PRs: https://github.com/godotengine/godot/pull/55139, https://github.com/godotengine/godot/issues/55138
Linux's `<sys/timex.h>` header was used instead of FreeBSD's <sys/time.h> due to missing preprocessor comparison.

Fix compilation on FreeBSD

---

encoder/basisu_kernels_sse.cpp

I tried building KTX-Software for Android x86_64 and for some reason the Android NDK's compiler sets the define `__SSE4_2__` even though the SSE version is specified via `-msse4.1`:
```bash
$ /path/to/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=x86_64-none-linux-android24 -msse4.1 -dM -E - < /dev/null | egrep "SSE|AVX" | sort
#define __SSE__ 1
#define __SSE2__ 1
#define __SSE2_MATH__ 1
#define __SSE3__ 1
#define __SSE4_1__ 1
#define __SSE4_2__ 1
#define __SSE_MATH__ 1
#define __SSSE3__ 1
```
Removing paramter `--target=x86_64-none-linux-android24` would solve it, but this is added by the CMake Android toolchain and I'm afraid beyond my control.
This brings me to my question: Does this absolutely have to fail if `__SSE4_2__` is set? With the suggested change …

fix: Allow building SSE kernels regardless of SSE 4.2 being (in)active

---

encoder/basisu_frontend.cpp

total_clusters_processed and total_selector_clusters aren't used in the lambda; total_clusters_processed is never used in general.

Fix clang warnings

---

contrib/single_file_transcoder/README.md
contrib/single_file_transcoder/basisu_transcoder-in.cpp
contrib/single_file_transcoder/combine.py
contrib/single_file_transcoder/create_transcoder.sh

The amalgamation script to generate the single-file transcoder was extremely slow and didn't run well (or at all) on Windows. This reimplementation in Python performs the same functions, has the same command-line args, but in testing is over 1000x faster.
More details here with timings: https://github.com/facebook/zstd/pull/3005

Replace the slow single-file shell script with a faster Python equivalent

---

transcoder/basisu_transcoder.cpp

This is a one character change but it was triggering issues when parsing the code as UTF-8.
Which triggers this when pre-processing the source with Python's parser:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 5297: invalid start byte
```
A regular text editor ignores it.

Minor: invalid char triggers Unicode error

---

README.md
basisu_tool.cpp

A more flexible variant of `-etc1_only`.
Works well with `-ktx_only` to produce a specific output.
Fixes the remaining part of #227

Add `-format_only` option

---

encoder/basisu_enc.cpp

This avoids the race condition in interval_timer::init which triggers
thread sanitizer errors.
Fixes #317.

Ensure interval_timer is initialized from main thread

---

encoder/basisu_enc.cpp

See https://github.com/emscripten-core/emscripten/pull/17704 for details.

emscripten no longer provides sys/timex.h, but does provide sys/time.h

---

transcoder/basisu_transcoder_internal.h

`huffman_decoding_table::init` allowed code lengths like `[0, 0]`, which should be invalid. Alternatively, if such inputs are valid this should be documented.

Disallow all-zero-length Huffman tables

---

encoder/basisu_kernels_sse.cpp

SSE4.1 support is checked at runtime, so compile time checks are redundant at best and harmful when compiling for a different machine.
Further more, a logic error prevented the use of SSE4.1 on systems with any version of AVX available. This is fixed now.
Fixes: https://github.com/BinomialLLC/basis_universal/issues/342

SIMD: disable compile time checks

---

transcoder/basisu_containers.h

To force `std::is_trivially_copyable`.
Allows the library consumer to resolve issues with some build environments (for example, Clang-based build environments) that may actually provide `std::is_trivially_copyable` but may also define `__GNUC__` (< 5).
The latest versions of Clang (Clang 15+) may trigger a warning / error without this, as they have deprecated `__has_trivial_copy` and will throw `-Wdeprecated-builtins` @richgel999
Example:
```
Error: .../transcoder/basisu_containers.h:745:19: error: builtin __has_trivial_copy is deprecated; use __is_trivially_copyable instead [-Werror,-Wdeprecated-builtins]
if ((!BASISU_IS_BITWISE_COPYABLE(T)) || (BASISU_HAS_DESTRUCTOR(T)))
^
.../transcoder/basisu_containers.h:198:88: note: expanded from macro 'BASISU_IS_BITWISE_COPYABLE'
#define …
```

Allow defining BASISU_HAVE_STD_TRIVIALLY_COPYABLE

---

encoder/basisu_comp.cpp

Regression since HDR merge; m_status_output = false should result in no prints outside of error cases.
Previously fixed in https://github.com/BinomialLLC/basis_universal/pull/239.

Fix verbose printfs when m_status_output = false

---

encoder/3rdparty/tinyexr.h

calloc takes sizeof as the second argument.

Fix gcc's calloc-transposed-args warning

---

transcoder/basisu_containers_impl.h

The file uses `isdigit` and `isalpha` from `ctype.h`, and recent MSVC seems to require it explicitly.
I haven't reproduced this myself, but got two Godot users the past week reporting these errors building Godot (which includes basisu) with MSVC:
```
P:\godot\thirdparty\basis_universal\transcoder\basisu_containers_impl.h(479): error C3861: 'isdigit': identifier not found
P:\godot\thirdparty\basis_universal\transcoder\basisu_containers_impl.h(482): error C3861: 'isalpha': identifier not found
P:\godot\thirdparty\basis_universal\transcoder\basisu_containers_impl.h(518): error C3861: 'isalpha': identifier not found
P:\godot\thirdparty\basis_universal\transcoder\basisu_containers_impl.h(541): error C3861: 'isalpha': identifier not found …
```

Add missing `ctype.h` include for transcoder/basisu_containers_impl.h

---

encoder/basisu_astc_hdr_6x6_enc.h

This PR changes `²` (U+00B2) to `^2` in one comment inside `encoder/basisu_astc_hdr_6x6_enc.h`.
This change is warranted by the fact that code editors may have a problem with supporting `²` (custom fonts may not render it at all, for example). As seen in https://github.com/godotengine/godot/pull/103968, compilers may not play nicely with it either.

Change `²` (U+00B2) to `^2`

---

transcoder/basisu_containers.h

When updating `basis_universal` to version 1.60 in Godot (https://github.com/godotengine/godot/pull/103968), I came across a compiler error about function call ambiguity.
This PR resolves said compile-time ambiguities. The issue occurs because the literal `1ULL` can be converted to both `uint32_t` and `uint64_t`, causing two overloads of `safe_shift_left()` (one for each type) to be viable.
I've explicitly cast the literal to `uint64_t` to fix the ambiguity.

Fix ambiguous calls to `safe_shift_left()` in `basisu_containers.h`

---

CMakeLists.txt

C++ only formally got "if constexpr" in C++17.  VC++ enforces this, and so when using basis_universal with Visual Studio in its CMake mode, the build is broken.  This fixes the build.

CMake: Fixed VS build by setting the C++ standard to 17 for "if constexpr".

---

transcoder/basisu_astc_helpers.h

transcoder/basisu_astc_helpers.h has a pragma once, but it is also an implementation header (when ASTC_HELPERS_IMPLEMENTATION is defined).
pragma once is not necessary here as the header has a separate ifdef guard, and it blocks attempts to compile Basis as a CMake Unity build (CMAKE_UNITY_BUILD=ON) or as a single-translation unit non-CMake build if the helpers header has been included earlier in the TU, as the second inclusion with implementation defined doesn't actually include the header.

Fix CMake Unity builds
